//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiKhachSan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLiKhachSanEntities : DbContext
    {
        public QuanLiKhachSanEntities()
            : base("name=QuanLiKhachSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangLuong> BangLuong { get; set; }
        public virtual DbSet<BangThuePhong> BangThuePhong { get; set; }
        public virtual DbSet<BoPhan> BoPhan { get; set; }
        public virtual DbSet<ChucDanh> ChucDanh { get; set; }
        public virtual DbSet<DichVu> DichVu { get; set; }
        public virtual DbSet<HoaDonThu> HoaDonThu { get; set; }
        public virtual DbSet<HoiVien> HoiVien { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LoaiDichVu> LoaiDichVu { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhong { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhanHoi> PhanHoi { get; set; }
        public virtual DbSet<Phong> Phong { get; set; }
        public virtual DbSet<TinhTrang> TinhTrang { get; set; }
        public virtual DbSet<TrangThaiThuePhong> TrangThaiThuePhong { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
